import {
  Injectable,
  NotFoundException,
  ForbiddenException,
  BadRequestException,
  Logger,
} from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { CreateDoubtDto } from './dto/create-doubt.dto';
import { SolveDoubtDto } from './dto/solve-doubt.dto';

@Injectable()
export class DoubtsService {
  private readonly logger = new Logger(DoubtsService.name);

  constructor(private prisma: PrismaService) {}

  async create(dto: CreateDoubtDto, studentId: string) {
    return this.prisma.doubt.create({
      data: {
        studentId,
        questionText: dto.questionText,
        questionImage: dto.questionImage,
        subject: dto.subject,
        chapter: dto.chapter,
        status: 'OPEN',
      },
      include: {
        student: { select: { id: true, name: true } },
      },
    });
  }

  async findAll(
    currentUser: any,
    page = 1,
    limit = 20,
    status?: string,
  ) {
    const skip = (page - 1) * limit;
    const where: any = {};

    if (status) where.status = status;

    // Students see their own doubts, teachers/solvers see available ones
    if (currentUser.role === 'STUDENT') {
      where.studentId = currentUser.id;
    }

    const [doubts, total] = await Promise.all([
      this.prisma.doubt.findMany({
        where,
        skip,
        take: limit,
        orderBy: { createdAt: 'desc' },
        include: {
          student: { select: { id: true, name: true } },
          assignedSolver: { select: { id: true, name: true } },
        },
      }),
      this.prisma.doubt.count({ where }),
    ]);

    return {
      doubts,
      pagination: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  async findOne(id: string) {
    const doubt = await this.prisma.doubt.findUnique({
      where: { id },
      include: {
        student: { select: { id: true, name: true, email: true } },
        assignedSolver: { select: { id: true, name: true, email: true } },
      },
    });

    if (!doubt) {
      throw new NotFoundException('Doubt not found');
    }

    return doubt;
  }

  async generateAiAnswer(id: string) {
    const doubt = await this.prisma.doubt.findUnique({ where: { id } });

    if (!doubt) {
      throw new NotFoundException('Doubt not found');
    }

    // STUB: In production, this would call OpenAI/Gemini API
    const aiResponse = `AI Generated Answer for: "${doubt.questionText}"\n\n` +
      `Based on the topic ${doubt.subject || 'General'} - ${doubt.chapter || 'General'}:\n\n` +
      `This is a placeholder AI response. In production, this would be generated by an AI model ` +
      `like GPT-4 or Gemini Pro, providing a detailed step-by-step solution.`;

    const updated = await this.prisma.doubt.update({
      where: { id },
      data: {
        aiResponse,
        status: 'AI_ANSWERED',
      },
    });

    this.logger.log(`AI answer generated for doubt: ${id}`);
    return updated;
  }

  async claimDoubt(id: string, solverId: string) {
    const doubt = await this.prisma.doubt.findUnique({ where: { id } });

    if (!doubt) {
      throw new NotFoundException('Doubt not found');
    }

    if (doubt.assignedSolverId) {
      throw new BadRequestException('Doubt is already claimed by another solver');
    }

    if (doubt.studentId === solverId) {
      throw new BadRequestException('You cannot solve your own doubt');
    }

    return this.prisma.doubt.update({
      where: { id },
      data: { assignedSolverId: solverId },
    });
  }

  async solveDoubt(id: string, dto: SolveDoubtDto, solverId: string) {
    const doubt = await this.prisma.doubt.findUnique({ where: { id } });

    if (!doubt) {
      throw new NotFoundException('Doubt not found');
    }

    if (doubt.assignedSolverId !== solverId) {
      throw new ForbiddenException('You are not assigned to this doubt');
    }

    return this.prisma.doubt.update({
      where: { id },
      data: {
        solverResponse: dto.response,
        status: 'HUMAN_ANSWERED',
      },
    });
  }

  async rateDoubt(id: string, rating: number, studentId: string) {
    const doubt = await this.prisma.doubt.findUnique({ where: { id } });

    if (!doubt) {
      throw new NotFoundException('Doubt not found');
    }

    if (doubt.studentId !== studentId) {
      throw new ForbiddenException('Only the student who asked can rate');
    }

    if (!['AI_ANSWERED', 'HUMAN_ANSWERED'].includes(doubt.status)) {
      throw new BadRequestException('Doubt has not been answered yet');
    }

    return this.prisma.doubt.update({
      where: { id },
      data: {
        rating,
        status: 'RESOLVED',
        resolvedAt: new Date(),
      },
    });
  }
}
