export function generateQuestionPaperHtml(test: any, institute: any): string {
  const instituteName = institute?.name || 'JEE SaaS Platform';
  const instituteLogo = institute?.logo || '';
  const brandColor = institute?.brandPrimaryColor || '#6366f1';

  const questionsHtml = generateQuestionsBody(test);

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Times New Roman', serif; padding: 40px; font-size: 12pt; line-height: 1.6; }
    .header { text-align: center; border-bottom: 3px solid ${brandColor}; padding-bottom: 15px; margin-bottom: 20px; }
    .header h1 { font-size: 20pt; color: ${brandColor}; }
    .header h2 { font-size: 14pt; color: #333; margin-top: 5px; }
    .meta { display: flex; justify-content: space-between; margin-bottom: 20px; padding: 10px; background: #f5f5f5; border-radius: 5px; }
    .meta-item { font-size: 10pt; }
    .section { margin-top: 25px; }
    .section-title { font-size: 14pt; font-weight: bold; color: ${brandColor}; border-bottom: 1px solid #ddd; padding-bottom: 5px; margin-bottom: 15px; }
    .question { margin-bottom: 15px; page-break-inside: avoid; }
    .question-number { font-weight: bold; }
    .question-text { margin-left: 25px; }
    .options { margin-left: 40px; margin-top: 5px; }
    .option { margin-bottom: 3px; }
    .difficulty-badge { display: inline-block; font-size: 8pt; padding: 1px 6px; border-radius: 3px; margin-left: 5px; }
    .difficulty-EASY { background: #d1fae5; color: #065f46; }
    .difficulty-MEDIUM { background: #fef3c7; color: #92400e; }
    .difficulty-HARD { background: #fee2e2; color: #991b1b; }
    .footer { margin-top: 30px; text-align: center; font-size: 9pt; color: #666; border-top: 1px solid #ddd; padding-top: 10px; }
    .qr-container { text-align: right; margin-top: 10px; }
    @media print { body { padding: 20px; } }
  </style>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css">
</head>
<body>
  <div class="header">
    ${instituteLogo ? `<img src="${instituteLogo}" alt="Logo" style="height:50px;margin-bottom:10px;">` : ''}
    <h1>${instituteName}</h1>
    <h2>${test.title}</h2>
  </div>

  <div class="meta">
    <span class="meta-item"><strong>Duration:</strong> ${test.duration} minutes</span>
    <span class="meta-item"><strong>Total Marks:</strong> ${test.totalMarks}</span>
    <span class="meta-item"><strong>Type:</strong> ${test.type}</span>
    <span class="meta-item"><strong>Date:</strong> ${new Date().toLocaleDateString('en-IN')}</span>
  </div>

  <div class="instructions" style="margin-bottom:20px;padding:10px;background:#fff7ed;border-left:4px solid ${brandColor};font-size:10pt;">
    <strong>Instructions:</strong>
    <ul style="margin-left:20px;margin-top:5px;">
      <li>All questions are compulsory unless stated otherwise.</li>
      <li>Each correct answer carries positive marks as mentioned per section.</li>
      <li>Wrong answers may attract negative marking.</li>
      <li>Use of calculator is not permitted.</li>
    </ul>
  </div>

  ${questionsHtml}

  <div class="footer">
    <p>Generated by ${instituteName} | JEE SaaS Platform</p>
    <p>This is a computer-generated document.</p>
  </div>
</body>
</html>`;
}

function generateQuestionsBody(test: any): string {
  let html = '';
  let globalIndex = 1;

  if (test.sections && test.sections.length > 0) {
    for (const section of test.sections) {
      html += `<div class="section">`;
      html += `<div class="section-title">${section.name} (${section.marksPerQuestion || 4} marks each, -${section.negativeMarksPerQuestion || 1} for wrong)</div>`;

      for (const tq of section.questions || []) {
        const q = tq.question;
        html += renderQuestion(q, globalIndex++);
      }
      html += `</div>`;
    }
  } else if (test.questions && test.questions.length > 0) {
    html += `<div class="section">`;
    for (const tq of test.questions) {
      const q = tq.question;
      html += renderQuestion(q, globalIndex++);
    }
    html += `</div>`;
  }

  return html;
}

function renderQuestion(q: any, index: number): string {
  let html = `<div class="question">`;
  html += `<div><span class="question-number">Q${index}.</span> <span class="difficulty-badge difficulty-${q.difficulty}">${q.difficulty}</span></div>`;
  html += `<div class="question-text">${q.text}</div>`;

  if (q.questionImage) {
    html += `<div class="question-text"><img src="${q.questionImage}" style="max-width:300px;margin-top:5px;"></div>`;
  }

  if (q.type === 'MCQ' || q.type === 'MULTI_CORRECT') {
    html += `<div class="options">`;
    if (q.optionA) html += `<div class="option">(A) ${q.optionA}</div>`;
    if (q.optionB) html += `<div class="option">(B) ${q.optionB}</div>`;
    if (q.optionC) html += `<div class="option">(C) ${q.optionC}</div>`;
    if (q.optionD) html += `<div class="option">(D) ${q.optionD}</div>`;
    html += `</div>`;
  } else if (q.type === 'NUMERICAL') {
    html += `<div class="options"><em>Answer: ____________</em></div>`;
  }

  html += `</div>`;
  return html;
}

export function generateAnswerKeyHtml(test: any, institute: any): string {
  const instituteName = institute?.name || 'JEE SaaS Platform';
  const brandColor = institute?.brandPrimaryColor || '#6366f1';

  let answersHtml = '';
  let index = 1;

  const allQuestions: any[] = [];
  if (test.sections && test.sections.length > 0) {
    for (const section of test.sections) {
      for (const tq of section.questions || []) {
        allQuestions.push(tq.question);
      }
    }
  } else if (test.questions) {
    for (const tq of test.questions) {
      allQuestions.push(tq.question);
    }
  }

  for (const q of allQuestions) {
    answersHtml += `
    <tr>
      <td style="padding:8px;border:1px solid #ddd;text-align:center;">${index++}</td>
      <td style="padding:8px;border:1px solid #ddd;">${q.text.substring(0, 60)}${q.text.length > 60 ? '...' : ''}</td>
      <td style="padding:8px;border:1px solid #ddd;text-align:center;">${q.type}</td>
      <td style="padding:8px;border:1px solid #ddd;text-align:center;font-weight:bold;color:green;">
        ${q.type === 'NUMERICAL' ? q.numericalAnswer : q.correctAnswer}
      </td>
      <td style="padding:8px;border:1px solid #ddd;font-size:10pt;">${q.solution || '-'}</td>
    </tr>`;
  }

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; }
    .header { text-align: center; border-bottom: 3px solid ${brandColor}; padding-bottom: 15px; margin-bottom: 20px; }
    .header h1 { color: ${brandColor}; }
    table { width: 100%; border-collapse: collapse; }
    th { background: ${brandColor}; color: white; padding: 10px; text-align: left; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${instituteName} - Answer Key</h1>
    <h2>${test.title}</h2>
  </div>

  <table>
    <thead>
      <tr>
        <th style="width:5%;">#</th>
        <th style="width:35%;">Question</th>
        <th style="width:10%;">Type</th>
        <th style="width:10%;">Answer</th>
        <th style="width:40%;">Solution</th>
      </tr>
    </thead>
    <tbody>
      ${answersHtml}
    </tbody>
  </table>

  <div style="margin-top:30px;text-align:center;font-size:9pt;color:#666;">
    <p>Generated by ${instituteName} | JEE SaaS Platform</p>
  </div>
</body>
</html>`;
}
